GRANT CONNECT, TEMP ON DATABASE kolesole TO zhyltser;
GRANT ALL ON ALL TABLES IN SCHEMA public TO zhyltser;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO zhyltser;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO zhyltser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES TO zhyltser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO zhyltser;

GRANT CONNECT, TEMP ON DATABASE kolesole TO prokoyul;
GRANT ALL ON ALL TABLES IN SCHEMA public TO prokoyul;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO prokoyul;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO prokoyul;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES TO prokoyul;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO prokoyul;



















